[package]
name = "swap_channel"
description = "A parallel communication channel based on mem::swap."
version = "0.0.1"
edition = "2021"
license = "BSD-2-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
